USE_SINGLE_PRECISION=0 ## 1: SINGLE or 0: DOUBLE

FC=ifort
FFLAGS=-O3 -heap-arrays # -pg -fno-inline  -warn -stand f03 -CB -traceback -g -debug all
FCINCLUDE=/opt/intel/mkl/latest/include

OBJS=param_parser.o simulation_box.o \
     fft_mkl.o mkl_dfti.o mkl_trig_transforms.o \
     polymer_chain.o pseudo.o \
     circular_buffer.o anderson_mixing.o scft.o
TARGET=scft_mkl.out
SRCDIR=../../src

$(TARGET): $(SRCDIR)/scft_main.F90 $(OBJS)
	$(FC) $(FFLAGS) -o $@ -mkl -qopenmp $^
param_parser.o: $(SRCDIR)/param_parser.F90
	$(FC) $(FFLAGS) -o $@ -c $^
simulation_box.o: $(SRCDIR)/simulation_box.F90
	$(FC) $(FFLAGS) -o $@ -c $^
polymer_chain.o: $(SRCDIR)/polymer_chain.F90
	$(FC) $(FFLAGS) -o $@ -c $^
pseudo.o: $(SRCDIR)/mkl/pseudo.F90 fft_mkl.o
	$(FC) $(FFLAGS) -o $@ -c -mkl -qopenmp $(SRCDIR)/mkl/pseudo.F90 
fft_mkl.o: $(SRCDIR)/mkl/fft_mkl.F90 mkl_dfti.o mkl_trig_transforms.o
	$(FC) $(FFLAGS) -o $@ -c -mkl -qopenmp $(SRCDIR)/mkl/fft_mkl.F90
mkl_dfti.o: $(FCINCLUDE)/mkl_dfti.f90
	$(FC) $(FFLAGS) -o $@ -c -mkl $^ 
mkl_trig_transforms.o: $(FCINCLUDE)/mkl_trig_transforms.f90
	$(FC) $(FFLAGS) -o $@ -c -mkl $^
circular_buffer.o: $(SRCDIR)/mkl/circular_buffer.F90
	$(FC) $(FFLAGS) -o $@ -c $^
anderson_mixing.o: $(SRCDIR)/mkl/anderson_mixing.F90
	$(FC) $(FFLAGS) -o $@ -c $^
scft.o: $(SRCDIR)/scft.F90
	$(FC) $(FFLAGS) -o $@ -c $^
clean:
	rm -f *__*.*
	rm -f *.o
	rm -f *.mod
	rm -f fields_* *.txt
	rm -f *.out
