#ifndef CRYSFFT_SELECTOR_H_
#define CRYSFFT_SELECTOR_H_

#include <array>
#include <cmath>
#include <vector>
#include "Recursive3mFoldParity.h"
#include "SpaceGroup.h"

enum class CrysFFTChoice
{
    None,
    Recursive3m,
    PmmmDct,
    ObliqueZ
};

struct CrysFFTSelection
{
    CrysFFTChoice mode = CrysFFTChoice::None;
    bool can_pmmm = false;
    std::array<double, 9> m3_translations = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    bool can_oblique_z = false;
    int oblique_z_shift = 0;
    double oblique_z_translation = 0.0;
};

inline CrysFFTSelection select_crysfft_mode(
    const SpaceGroup* sg,
    const std::array<int, 3>& nx,
    int dim,
    bool is_periodic,
    bool is_orthogonal,
    bool z_axis_orthogonal)
{
    CrysFFTSelection selection;

    if (sg == nullptr || dim != 3 || !is_periodic)
        return selection;

    const bool even_grid = (nx[0] % 2 == 0 && nx[1] % 2 == 0 && nx[2] % 2 == 0);
    const bool even_z = (nx[2] % 2 == 0);

    std::array<double, 9> trans_part = {0, 0, 0, 0, 0, 0, 0, 0, 0};
    const bool has_3m = sg->get_m3_translations(trans_part);
    const bool has_pmmm = sg->has_mirror_planes_xyz();
    // Recursive3m grid condition: even grid, nz/2 >= 8, and a valid
    // translation-parity permutation (compute_m3_fold_permutation). The fold
    // pairs twiddle r_p with the octant-transformed Boltzmann array S_{psi(p)}
    // where psi depends on the parities of the m3 generator translations in
    // grid units (tau = t*N); psi must be a bijection.
    //
    // psi-bijectivity vs m3-basis feasibility (PROVEN equivalence with the
    // representative search below): the parity shift Delta(O) in {0,1}^3 of a
    // diagonal op O (Delta_d = (tau_d + [sign_d = -1]) mod 2) is a group
    // homomorphism into GF(2)^3, and psi(a) = Delta(O_a) for the product O_a
    // of the chosen generator representatives.
    //  (=>) psi bijective means the 8 products already realize every parity
    //       class, so every grid point maps to an even-index point and the
    //       basis construction succeeds.
    //  (<=) Basis feasibility means Delta over ALL diagonal ops is surjective,
    //       i.e. Delta(H) + Delta(C) = GF(2)^3 where H is generated by the
    //       minimal-norm mirror representatives and C are the pure
    //       (centering) translations. A Steinitz-exchange argument shows one
    //       can then always compose each generator with some c in C so that
    //       the composed psi is bijective; the search below tries all such
    //       compositions (|C|^3 <= 64), so rejection here implies the basis
    //       is genuinely infeasible. The gap can only open at all when some
    //       centering translation has odd grid parity (an axis with N = 2 mod
    //       4), since otherwise Delta(C) = {0} and the minimal representatives
    //       alone decide.
    // Historically the code hard-coded psi = identity, which silently
    // miscomputed grids with odd tau (e.g. Fddd 84x48x16/24/32, wrong Q at
    // ~0.6 relative); an interim guard restricted unequal grids to
    // all-quarters-even. With the psi pairing implemented in
    // CrysFFTRecursive3mBase/CudaCrysFFTRecursive3m, verified 2026-08:
    // - Unit level (one diffusion vs full-grid FFT reference, <= 1e-14 rel),
    //   MKL and FFTW: Fddd 84x48x16, 84x48x24, 84x48x32 (previously broken),
    //   84x56x16, 84x56x32 (odd qx); 64x52x16, 72x52x16 (odd qy); 64x48x84,
    //   72x56x84, 64x48x20, 64x48x12 (odd qz); 64x48x16, 88x48x24, 64x56x32,
    //   32x24x16, 32x24x8 (all even); Fddd 16/24/40/48^3; Im-3m 16/20/22/
    //   40/44^3. CUDA: 84x48x16, 64x52x16, 64x48x84, 64x48x12, Im-3m 40^3,
    //   including the k^2-multiplier (stress) caches.
    // - SCFT space-group ON-vs-OFF partition comparisons (<= 7e-14 rel):
    //   the trio on cpu-mkl AND cpu-fftw; 64x48x16, 84x56x16, 64x52x16,
    //   64x48x84 on cpu-mkl; Fddd 84x48x16, 64x48x84 and Im-3m 40^3 on cuda.
    // - Grids whose psi is singular for every representative choice (verified
    //   Fddd 44^3, 84^3, 84x48x84 — two or more odd quarters; Fddd's F
    //   centering has even parity on commensurate grids, so no composition
    //   can rescue them) are rejected here and fall back to the standard FFT
    //   path (still correct, per the same ON-vs-OFF probes), matching
    //   SpaceGroup m3-basis feasibility exactly.
    // nz/2 >= 8 is kept as the established performance/selection bound;
    // smaller nz still works via the standard path (the former buffer-overrun
    // reason is gone: the padded k-loop is now clamped to the row stride).
    const bool even_all = (nx[0] % 2 == 0) && (nx[1] % 2 == 0) && (nx[2] % 2 == 0);
    std::array<int, 8> fold_perm{};
    bool fold_ok = has_3m &&
        compute_m3_fold_permutation(trans_part, nx, fold_perm);
    if (has_3m && even_all && !fold_ok)
    {
        // Minimal-norm representatives give a singular psi. Search coset
        // representatives composed with the pure (centering) translations;
        // by the exchange argument above, if the m3 basis is feasible at all,
        // some composition yields a bijective psi. The engines recompute the
        // permutation from selection.m3_translations, so storing the composed
        // translations keeps the fold, its twiddles, and psi consistent.
        std::vector<std::array<double, 3>> centerings;
        sg->get_pure_translations(centerings);
        auto wrap01 = [](double v) {
            v -= std::floor(v);
            if (v < 0.0)
                v += 1.0;
            return v;
        };
        for (size_t cz = 0; cz < centerings.size() && !fold_ok; ++cz)
        for (size_t cy = 0; cy < centerings.size() && !fold_ok; ++cy)
        for (size_t cx = 0; cx < centerings.size() && !fold_ok; ++cx)
        {
            std::array<double, 9> composed = trans_part;
            for (int d = 0; d < 3; ++d)
            {
                composed[0 + d] = wrap01(trans_part[0 + d] + centerings[cz][d]);
                composed[3 + d] = wrap01(trans_part[3 + d] + centerings[cy][d]);
                composed[6 + d] = wrap01(trans_part[6 + d] + centerings[cx][d]);
            }
            if (compute_m3_fold_permutation(composed, nx, fold_perm))
            {
                trans_part = composed;
                fold_ok = true;
            }
        }
    }
    const bool recursive_ok = even_all && ((nx[2] / 2) >= 8) && fold_ok;

    selection.can_pmmm = has_pmmm;

    // Z-mirror (ObliqueZ): allow even for non-orthogonal cells when z-axis is orthogonal
    if (even_z && z_axis_orthogonal)
    {
        double tz = 0.0;
        const bool has_z_mirror = sg->get_z_mirror_translation(tz);
        if (has_z_mirror)
        {
            double t = tz;
            const double tol = 1e-8;
            if (std::fabs(t - 1.0) < tol)
                t = 0.0;
            if (std::fabs(t) < tol)
            {
                selection.can_oblique_z = true;
                selection.oblique_z_translation = t;
                selection.oblique_z_shift = 0;
            }
            else if (std::fabs(t - 0.5) < tol)
            {
                if ((nx[2] % 4) == 0)
                {
                    selection.can_oblique_z = true;
                    selection.oblique_z_translation = t;
                    selection.oblique_z_shift = nx[2] / 4;
                }
            }
        }
    }

    if (sg->using_z_mirror_physical_basis())
    {
        if (selection.can_oblique_z)
            selection.mode = CrysFFTChoice::ObliqueZ;
        return selection;
    }

    if (sg->using_pmmm_physical_basis())
    {
        if (has_pmmm)
            selection.mode = CrysFFTChoice::PmmmDct;
        return selection;
    }

    if (sg->using_m3_physical_basis())
    {
        if (has_3m && recursive_ok)
        {
            selection.mode = CrysFFTChoice::Recursive3m;
            selection.m3_translations = trans_part;
        }
        return selection;
    }

    if (!is_orthogonal)
    {
        selection.can_pmmm = false;
        return selection;
    }

    if (!even_grid)
        return selection;

    if (has_3m && recursive_ok)
    {
        selection.mode = CrysFFTChoice::Recursive3m;
        selection.m3_translations = trans_part;
        return selection;
    }

    if (has_pmmm)
        selection.mode = CrysFFTChoice::PmmmDct;

    if (selection.mode == CrysFFTChoice::None && selection.can_oblique_z)
        selection.mode = CrysFFTChoice::ObliqueZ;

    return selection;
}

#endif  // CRYSFFT_SELECTOR_H_
